# Generated by Django 6.1.1 on 2026-09-14 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('party_type', models.CharField(choices=[('MANUFACTURER', 'Manufacturer'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gpay_number', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, db_index=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyPaymentQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('qr_name', models.CharField(help_text='Example: HDFC QR, G-Pay QR, PhonePe QR', max_length=100)),
                ('qr_image', models.ImageField(upload_to='parties/payment_qr/')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qrs', to='dashboard.party')),
            ],
            options={
                'verbose_name': 'Party Payment QR',
                'verbose_name_plural': 'Party Payment QRs',
                'db_table': 'party_payment_qrs',
                'ordering': ['-is_primary', 'qr_name'],
            },
        ),
    ]
