# Generated by Django 6.1.1 on 2026-09-18 07:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_paymentmethod_partyorder_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('purchase_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('RECEIVED', 'Received'), ('PARTIAL', 'Partially Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('due_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Party Purchase',
                'verbose_name_plural': 'Party Purchases',
                'db_table': 'party_purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePaymentInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Purchase Payment Installment',
                'verbose_name_plural': 'Purchase Payment Installments',
                'db_table': 'purchase_payment_installments',
                'ordering': ['installment_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='partyorder',
            name='party_order_party_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='partyorder',
            name='party_order_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_order_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_status_date_idx',
        ),
        migrations.AddField(
            model_name='partypurchase',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='dashboard.party'),
        ),
        migrations.AddField(
            model_name='purchasepaymentinstallment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_installments', to='dashboard.paymentmethod'),
        ),
        migrations.AddField(
            model_name='purchasepaymentinstallment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='dashboard.partypurchase'),
        ),
        migrations.RemoveField(
            model_name='partyorder',
            name='party',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddConstraint(
            model_name='purchasepaymentinstallment',
            constraint=models.UniqueConstraint(fields=('purchase', 'installment_number'), name='unique_purchase_installment'),
        ),
        migrations.DeleteModel(
            name='PartyOrder',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
