# Generated by Django 6.1.1 on 2026-09-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_partypurchase_purchasepaymentinstallment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypurchase',
            name='purchase_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, unique=True),
        ),
    ]
