# Generated by Django 6.1.1 on 2026-09-18 09:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_partypurchase_purchase_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypurchase',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
    ]
