# Generated by Django 6.1.1 on 2026-09-18 10:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_partypurchase_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partypurchase',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter CGST percentage.', max_digits=5),
        ),
        migrations.AddField(
            model_name='partypurchase',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter discount percentage.', max_digits=5),
        ),
        migrations.AddField(
            model_name='partypurchase',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter IGST percentage.', max_digits=5),
        ),
        migrations.AddField(
            model_name='partypurchase',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter SGST percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transport, packing, shipping, etc.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], db_index=True, default='UNPAID', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchasepaymentinstallment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchasepaymentinstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', editable=False, max_length=20),
        ),
    ]
