# Generated by Django 6.1.1 on 2026-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_partypurchase_cgst_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partypurchase',
            name='bill_type',
            field=models.CharField(choices=[('GST', 'GST Bill'), ('NON_GST', 'Non-GST Bill')], db_index=True, default='GST', help_text='Select whether this is a GST or Non-GST bill.', max_length=10),
        ),
        migrations.AddField(
            model_name='partypurchase',
            name='invoice_document',
            field=models.FileField(blank=True, help_text='Upload supplier GST/Non-GST bill image or PDF.', null=True, upload_to='party_bills/%Y/%m/'),
        ),
    ]
