# Generated by Django 6.1.1 on 2026-09-27 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_partypurchase_bill_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Link Category',
                'verbose_name_plural': 'Quick Link Categories',
                'db_table': 'quick_link_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('url_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_links', to='dashboard.quicklinkcategory')),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'db_table': 'quick_links',
                'ordering': ['category__display_order', 'display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_quick_link_name_per_category')],
            },
        ),
    ]
