# Generated by Django 6.1.1 on 2026-09-28 11:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0008_quicklinkcategory_quicklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('GENERAL', 'General'), ('SYSTEM', 'System Update'), ('FESTIVAL', 'Festival Update'), ('FEATURE', 'New Feature'), ('ANNOUNCEMENT', 'Announcement'), ('PRODUCT', 'Product Update'), ('ORDER', 'Order Update'), ('PAYMENT', 'Payment Update'), ('WARNING', 'Warning'), ('SUCCESS', 'Success')], db_index=True, default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('icon', models.CharField(blank=True, default='ri-notification-3-line', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-is_pinned', '-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='dashboard.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='accounts.useraccount')),
            ],
            options={
                'db_table': 'notification_recipients',
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_c217c7_idx'), models.Index(fields=['notification', 'user'], name='notificatio_notific_27fbf1_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_user')],
            },
        ),
    ]
