# Generated by Django 6.1.1 on 2026-09-30 05:06

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_notification_notificationrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['category__display_order', 'display_order', 'name']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.dashboard.models.notification_image_upload_path),
        ),
        migrations.AlterField(
            model_name='partypaymentqr',
            name='qr_image',
            field=models.ImageField(upload_to=apps.dashboard.models.party_payment_qr_upload_path),
        ),
        migrations.AlterField(
            model_name='partypurchase',
            name='invoice_document',
            field=models.FileField(blank=True, help_text='Upload supplier GST/Non-GST bill image or PDF.', null=True, upload_to=apps.dashboard.models.party_purchase_invoice_upload_path),
        ),
    ]
