# Generated by Django 6.1.1 on 2026-09-28 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pdf_overlay/overlays/')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Overlay Image',
                'verbose_name_plural': 'Overlay Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
